apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: symptoma/activemq:5.16.3
        ports:
        - containerPort: 61616  # JMS
        - containerPort: 8161   # Web console
        env:
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: "admin"
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: "admin"
        - name: ACTIVEMQ_ENABLED_AUTH
          value: "true"
        - name: ACTIVEMQ_ENABLED_SCHEDULER
          value: "true"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  ports:
  - name: jms
    port: 61616
    targetPort: 61616
  - name: web
    port: 8161
    targetPort: 8161
  selector:
    app: activemq
  type: ClusterIP
