apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  namespace: oneagent-activemq
  labels:
    app: payment-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
      annotations:
        dynatrace.com/inject-oneagent: "true"
    spec:
      containers:
      - name: payment-processor
        image: ghcr.io/mreider/payment-processor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres.oneagent-activemq:5432/billingdb
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: MESSAGING_SYSTEM
          value: "activemq"
        - name: OPENTELEMETRY_ENABLED
          value: "false"
        - name: OTEL_SDK_DISABLED
          value: "true"
        - name: ACTIVEMQ_BROKER_URL
          value: "tcp://activemq.oneagent-activemq:61616"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: oneagent-activemq
spec:
  selector:
    app: payment-processor
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
