apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-simulator
  namespace: otel-rabbitmq
  labels:
    app: load-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-simulator
  template:
    metadata:
      labels:
        app: load-simulator
    spec:
      containers:
      - name: load-simulator
        image: ghcr.io/mreider/load-simulator:latest
        imagePullPolicy: Always
        env:
        - name: BILLING_SERVICE_URL
          value: "http://billing-service.otel-rabbitmq:8080"
        - name: OPENTELEMETRY_ENABLED
          value: "true"
        - name: OTEL_SDK_DISABLED
          value: "false"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: DYNATRACE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-secret
              key: endpoint
        - name: DYNATRACE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-secret
              key: api-token
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
