apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-simulator
  namespace: oneagent-kafka
  labels:
    app: load-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-simulator
  template:
    metadata:
      labels:
        app: load-simulator
      annotations:
        dynatrace.com/inject-oneagent: "true"
    spec:
      containers:
      - name: load-simulator
        image: ghcr.io/mreider/load-simulator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: OPENTELEMETRY_ENABLED
          value: "false"
        - name: OTEL_SDK_DISABLED
          value: "true"
        - name: BILLING_SERVICE_URL
          value: "http://billing-service.oneagent-kafka:8080"
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: load-simulator
  namespace: oneagent-kafka
spec:
  selector:
    app: load-simulator
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
