name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: mreider

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push billing-service image
        uses: docker/build-push-action@v4
        with:
          context: ./src/billing-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/billing-service:latest

      - name: Build and push payment-processor image
        uses: docker/build-push-action@v4
        with:
          context: ./src/payment-processor
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/payment-processor:latest

      - name: Build and push invoice-aggregator image
        uses: docker/build-push-action@v4
        with:
          context: ./src/invoice-aggregator
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/invoice-aggregator:latest

      - name: Build and push load-simulator image
        uses: docker/build-push-action@v4
        with:
          context: ./src/load-simulator
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/load-simulator:latest
